name: Java CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306
        volumes:
          - /tmp/mysql:/var/lib/mysql

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Install MySQL Client
        run: sudo apt-get install mysql-client

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run Tests
        run: mvn test --file pom.xml
        env:
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_NAME: testdb
          DB_USER: root
          DB_PASSWORD: root

      - name: Generate Javadoc
        run: mvn javadoc:javadoc

      - name: Publish Javadoc
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: target/docs/javadoc
